version: '3'

services:
  ping-service-1:
    build:
      context: ./EX4
      dockerfile: Dockerfile.serveur1
    ports:
      - "7100:4567"
    networks:
      - alpine-net
      - ping-net-1
    container_name: server1
    command: ["python", "-u", "serveur1.py"]

  pong-service-1:
    build:
      context: ./EX4
      dockerfile: Dockerfile.serveur2
    ports:
      - "7106:5372"
    networks:
      - alpine-net
      - pong-net-1
    container_name: serveur2
    command: ["python", "-u", "serveur2.py"]
    depends_on:
      - ping-service-1

  ping-service-2:
    build:
      context: ./EX4
      dockerfile: Dockerfile.serveur1
    ports:
      - "7101:4567"
    networks:
      - alpine-net
      - ping-net-2
    container_name: server1_instance_2
    command: ["python", "-u", "serveur1.py"]

  pong-service-2:
    build:
      context: ./EX4
      dockerfile: Dockerfile.serveur2
    ports:
      - "7107:5372"
    networks:
      - alpine-net
      - pong-net-2
    container_name: serveur2_instance_2
    command: ["python", "-u", "serveur2.py"]
    depends_on:
      - ping-service-2

networks:
  alpine-net:
    driver: bridge

  ping-net-1:
    driver: bridge

  pong-net-1:
    driver: bridge

  ping-net-2:
    driver: bridge

  pong-net-2:
    driver: bridge
